# Generated by Django 2.0.4 on 2018-04-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complainant_name', models.CharField(max_length=60)),
                ('place_event', models.CharField(max_length=120)),
                ('complaint_date', models.DateField(auto_now_add=True)),
                ('event_date_time', models.DateTimeField()),
                ('description', models.TextField()),
                ('evidence', models.CharField(max_length=200)),
            ],
        ),
    ]
