# Generated by Django 2.0.4 on 2018-05-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complainant_name', models.CharField(max_length=60)),
                ('place_event', models.CharField(max_length=120)),
                ('complaint_date', models.DateField(auto_now_add=True)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('description', models.TextField()),
                ('license_plate', models.CharField(blank=True, max_length=8, null=True)),
                ('evidence', models.CharField(blank=True, max_length=200, null=True)),
                ('ranking', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
